site_description: Vue.js - The Progressive JavaScript Framework
google_analytics: UA-46852172-3
root_domain: cn.vuejs.org
vue_version: 2.6.14
# START SPONSORS
special:
  - name: HBuilder
    url: https://www.dcloud.io/hbuilderx.html?hmsr=vue-en&hmpl=&hmcu=&hmkw=&hmci=
    img: hbuilder.png
    description: An IDE for Vue
platinum:
  - name: VueMastery
    url: https://www.vuemastery.com/
    img: vuemastery.png
  - name: VueSchool
    url: >-
      https://vueschool.io/?utm_source=Vuejs.org&utm_medium=Banner&utm_campaign=Sponsored%20Banner&utm_content=V1
    img: vueschool.png
  - name: Vehikl
    url: https://vehikl.com/
    img: vehikl.png
  - name: Passionate People
    url: https://passionatepeople.io/
    img: passionate_people.png
  - name: Storyblok
    url: https://www.storyblok.com
    img: storyblok.png
  - name: Ionic
    url: >-
      https://ionicframework.com/vue?utm_source=partner&utm_medium=referral&utm_campaign=vuesponsorship&utm_content=vuedocs
    img: ionic.png?v2
  - name: Nuxt
    url: https://nuxtjs.org/
    img: nuxt.png
  - name: Refurbed
    url: https://www.refurbed.org/?utm_source=vuejs
    img: refurbed.png
  - name: ButterCMS
    url: >-
      https://buttercms.com/vuejs-cms/?utm_source=vuejs.org&utm_medium=banner&utm_campaign=sponsorship
    img: buttercms.svg
  - name: Sanofi
    url: https://www.sanofi.com/
    img: sanofi.png
  - name: CodeDict
    url: https://code-dict.com
    img: codedict.svg
  - name: vuejs.de Conf
    url: >-
      https://conf.vuejs.de/?utm_source=vuejs-vite&utm_medium=referral&utm_campaign=sponsoring
    img: vuejs_de_conf.svg
platinum_china:
  - name: HBuilder
    url: https://www.dcloud.io/hbuilderx.html?hmsr=vue-en&hmpl=&hmcu=&hmkw=&hmci=
    img: hbuilder.png
  - name: 稀土掘金技术社区
    url: https://juejin.cn/frontend?utm_source=vue&utm_campaign=sponsor
    img: xitujuejinjishushequ.png
gold:
  - name: Laravel
    url: https://laravel.com
    img: laravel.png
  - name: HTML Burger
    url: https://htmlburger.com
    img: html_burger.png
  - name: Neds
    url: https://neds.com.au/
    img: neds.png
  - name: Tidelift
    url: https://tidelift.com/subscription/npm/vue
    img: tidelift.png
  - name: Firestick Tricks
    url: https://www.firesticktricks.com/
    img: firestick_tricks.png
  - name: Intygrate
    url: https://intygrate.com/
    img: intygrate.png
  - name: Bacancy Technology
    url: https://www.bacancytechnology.com/hire-vuejs-developer
    img: bacancy_technology.png
  - name: Y8
    url: https://www.y8.com/
    img: y8.png
  - name: DevExpress
    url: https://js.devexpress.com/
    img: devexpress.png
  - name: FASTCODING Inc
    url: 'https://fastcoding.jp/javascript/ '
    img: fastcoding_inc.svg
  - name: VPSServer.com
    url: https://www.vpsserver.com
    img: vpsserver_com.png
  - name: LINE Corporation
    url: https://linecorp.com
    img: line_corporation.png
  - name: PLAID, Inc.
    url: https://plaid.co.jp/
    img: plaid__inc_.svg
  - name: EMQ
    url: https://www.emqx.com
    img: emq.png
  - name: Onyx Gaming Limited
    url: https://www.aceonlinecasino.co.uk
    img: onyx_gaming_limited.svg
  - name: Lendio
    url: http://www.lendio.com
    img: lendio.png
  - name: Fenêtre Online Solutions
    url: https://www.fenetre.nl/
    img: fen_tre_online_solutions.svg
  - name: MyEtherWallet Inc
    url: https://www.myetherwallet.com
    img: myetherwallet_inc.png
  - name: Barrage
    url: https://www.barrage.net
    img: barrage.png
  - name: Ant Design Vue
    url: https://antdv.com
    img: ant_design_vue.png
  - name: Lemon Law
    url: https://lemonlaw.site
    img: lemon_law.png
  - name: MQTT X
    url: https://mqttx.app
    img: mqtt_x.png
  - name: Crisp
    url: https://crisp.chat/en/
    img: crisp.png
  - name: Cypress.io
    url: https://cypress.io
    img: cypress_io.svg
  - name: QuickBooks Tool Hub
    url: https://quickbookstoolhub.com
    img: quickbooks_tool_hub.png
  - name: Snyk
    url: https://snyk.co/vuejs
    img: snyk.png?v2
  - name: Handsontable - JavaScript Data Grid
    url: https://handsontable.com/
    img: handsontable___javascript_data_grid.svg
  - name: 1Tool
    url: https://www.1tool.com
    img: 1tool.png
silver:
  - name: Draxlr
    url: https://www.draxlr.com
    img: draxlr.svg
  - name: iSolutions UK Limited
    url: https://www.thecasinodb.com
    img: isolutions_uk_limited.png
  - name: Team Extension North America Inc
    url: https://teamextension.io
    img: team_extension_north_america_inc.png
  - name: Free Bets US
    url: https://freebets.us
    img: free_bets_us.png
  - name: Doximity
    url: https://technology.doximity.com/
    img: doximity.png
  - name: CircleCI
    url: https://circleci.com/open-source/
    img: circleci.png
  - name: Interflora Group
    url: https://www.interflora.fr
    img: interflora_group.png
  - name: Localazy
    url: >-
      https://localazy.com/blog/how-to-localize-vuejs-app-with-vue-i18n-and-localazy?utm_source=vuejs&utm_medium=banner&utm_campaign=sponsorships_vuejs&utm_content=logo
    img: localazy.png
  - name: AddWeb Solution
    url: http://addwebsolution.com/
    img: addweb_solution.png?v2
  - name: 1394TA
    url: https://1394ta.org
    img: 1394ta.png
bronze:
  - name: Derek Pollard
    url: https://polyglotengineer.com/derek.pollard
    img: derek_pollard.png
  - name: Earthlink
    url: https://www.earthlink.ro
    img: earthlink.png
  - name: BGASoft
    url: https://www.bgasoft.com
    img: bgasoft.png
  - name: RStudio
    url: https://rstudio.com
    img: rstudio.png
  - name: Custouch Marketing Automation
    url: http://www.custouch.com
    img: custouch_marketing_automation.png
  - name: Darkhorse Analytics
    url: https://www.darkhorseanalytics.com/
    img: darkhorse_analytics.png
  - name: vuejs.de - German Vue Community
    url: https://vuejs.de
    img: vuejs_de___german_vue_community.svg
  - name: Liip AG
    url: https://www.liip.ch/en
    img: liip_ag.png
  - name: Monarch Air Group
    url: https://monarchairgroup.com
    img: monarch_air_group.png
# END SPONSORS
video_china:
  - url: http://cloud.youku.com/index.php?source=vuejs
    img: youku.png
