name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ^7.4.0

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run build

      - run: |
          cd public
          git init
          git config user.email "yyx990803@gmail.com"
          git config user.name "Evan You"
          git add .
          git commit -m "update docs"
          git remote add github https://yyx990803:${{ secrets.GITHUB_TOKEN }}@github.com/vuejs/cn.vuejs.org.git
          git push github HEAD:gh-pages --force
          git remote add gitee https://yyx990803:${{ secrets.GITEE_TOKEN }}@gitee.com/vuejs-cn/vue2-docs-cn.git
          git push gitee HEAD:master --force
